version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

engines:
  stylelint:
    enabled: true   
  eslint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - "src/**.js"
    - "src/**.less"

exclude_paths:
  - bin
  - node_modules
  - typings
  - coverage
  - dist