version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 1
  similar-code:
    enabled: true
  identical-code:
    enabled: true

plugins:
  stylelint:
    enabled: true   
  fixme:
    enabled: true
  eslint:
    enabled: true

ratings:
  paths:
    - "src/**.js"
    - "src/**.less"

exclude_paths:
  - "bin"
  - "node_modules"
  - "typings"
  - "coverage"
  - "dist"