language: node_js

node_js:
  - '8'

sudo: false

before_script:
  - npm install

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: "Test"
      script: npm run test-ci
    - stage: "Build"
      script: npm run build