language: node_js

node_js:
  - '8'

sudo: false

jobs:
  include:
    - stage: "Install Dependencies"
      script: npm install
    - stage: "Test"
      script: npm run testc
    - stage: "Build"
      script: npm run build