language: node_js

node_js:
  - '10'

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - 'node_modules'

jobs:
  include:
    - stage: "Install Dependencies"
      script: yarn
    - stage: "Test"
      script: yarn testc
    - stage: "Build"
      script: yarn build