sudo: required
# language: node_js
# node_js:
# - "6"

services:
- docker

# before_install:
# - npm install -g npm
# - npm install -g greenkeeper-lockfile@1

before_script: 
# - greenkeeper-lockfile-update
- docker build -t vcr/latest --build-arg CODECLIMATE_REPO_TOKEN=$TRAVIS_CODECLIMATE_TOKEN .
- docker run -d --name vc-react-container vcr/latest

script:
- docker ps -a

# after_script: 
# - greenkeeper-lockfile-upload