sudo: required
# language: node_js
# node_js:
# - "6"

services:
- docker

# before_install:
# - npm install -g npm
# - npm install -g greenkeeper-lockfile@1

before_script: 
# - greenkeeper-lockfile-update
- docker build -t vcr/latest .
- docker run -d --name vc-react-container vcr/latest -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_CODECLIMATE_TOKEN=$TRAVIS_CODECLIMATE_TOKEN

script:
- docker ps -a

# after_script: 
# - greenkeeper-lockfile-upload